### ISSUE TITLE
Support x86-32 to fuzz emulators that don't support x86-64

### ISSUE THREAD

**Issue by bachimusprime** [blitz/baresifter#2]
I would like to fuzz MAME's i386 core using this tool, but unfortunately, this only works on 64-bit CPUs, and MAME's emulation simply hasn't gotten that far yet. I also can't run sandsifter since most modern Unices require at least a Pentium if not a Pentium Pro to install, and MAME's emulation of PCs based on those CPUs is shoddy currently at best.

**Comment by blitz** [comment]
That's a good suggestion. I don't have much time to work on this, but would be happy to help anyone trying to implement this.

**Comment by blitz** [comment]
There is some slight update here. 32-bit at least links and starts. But it's still not done yet. Let's see whether I get it fixed.

**Comment by superfury** [comment]
I've managed to get some 32-bit older CPU support (theoretically on 486 and lower) implemented. Haven't been able to verify yet on a 486 due to my loader program (SYSLINUX 6.04 CHS 20191223 floppy disk image) using Pentium NOP opcodes I think (opcode F30F1E), which causes it to crash before loading the program.

The current code is at:
https://github.com/superfury/baresifter

I've added CPUID detection (using the EFLAGS ID bit only though). I've also added some other checks for the various features of the CPU that are giving issues on my Pentium/Pentium Pro emulator (some of the CR4 bits that weren't supported according to it's reported CPUID results, so those are added).
It also, if CPUID isn't supported, simply returns all zeroes in the CPUID results, causing those features to be detected as non-present.
And I've implemented a simple 4KB page table mapping (although the code is unverified due to the above loader issue) for when a CPU without PSE is detected (so it properly should fall back onto creating some extra page tables in memory, at the end of the loaded ELF executable, rounded up towards 4KB) when mapping in the executable itself.

The 386 support (it's still using the WP bit, which crashes it on such a system) might be detected by using the same method as the CPUID detection, but using the alignment flag instead (it performs a simple XOR on said bit and detects if it changed). That should trigger clearing of the WP bit in CR0 if done that way.
I don't know how that would affect the pure assembly loading process though. Perhaps it can start in protected mode without it enabled and enable it when setting up paging?
Edit: Implemented that as well. So it should in theory run on a 386, 486, Pentium and anything newer with those changes (386 assuming it can run without the WP bit in CR0 set). And ofc requiring an ELF loader supporting those CPUs.
The main issue is that it's compiled with i686 architecture maybe (it seems to run without issues in my i440fx Pentium Pro testcase, but no guarantees on what instructions the compiler decides to use).
